### ISSUE TITLE
game Crashed when using Block Breaker in 1.16.4

### ISSUE THREAD

**Issue by RedSeaObject** [Shnupbups/redstone-bits#13]
game crashed when activating block breaker. Redstone Bits Version 1.3.0. Crash Report below:

java.lang.NoSuchMethodError: net.minecraft.class_1657.<init>(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lcom/mojang/authlib/GameProfile;)V
	at com.shnupbups.redstonebits.FakePlayerEntity.<init>(FakePlayerEntity.java:18)
	at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.breakBlock(BreakerBlockEntity.java:137)
	at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.finishBreak(BreakerBlockEntity.java:116)
	at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.method_16896(BreakerBlockEntity.java:165)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.handler$dci000$modifiedRunLoop(MinecraftServer.java:5310)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$6999/517051772.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.shnupbups.redstonebits.FakePlayerEntity.<init>(FakePlayerEntity.java:18)
	at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.breakBlock(BreakerBlockEntity.java:137)
	at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.finishBreak(BreakerBlockEntity.java:116)
	at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.method_16896(BreakerBlockEntity.java:165)

-- Block entity being ticked --
Details:
	Name: redstonebits:breaker // com.shnupbups.redstonebits.blockentity.BreakerBlockEntity
	Block: Block{redstonebits:breaker}[triggered=true,breaking=true,facing=north]
	Block location: World: (33,64,159), Chunk: (at 1,4,15 in 2,9; contains blocks 32,0,144 to 47,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{redstonebits:breaker}[triggered=true,breaking=true,facing=north]
	Block location: World: (33,64,159), Chunk: (at 1,4,15 in 2,9; contains blocks 32,0,144 to 47,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Dead_E'/138, l='ServerLevel[New World]', x=31.61, y=64.00, z=162.66]]
	Chunk stats: ServerChunkCache: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,64,160), Chunk: (at 0,4,0 in 2,10; contains blocks 32,0,160 to 47,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 21882 game time, 21882 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 43784 (now: false), thunder time: 140897 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.handler$dci000$modifiedRunLoop(MinecraftServer.java:5310)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$6999/517051772.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1878184952 bytes (1791 MB) / 3225419776 bytes (3076 MB) up to 7456948224 bytes (7111 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		allstackable: All Stackable 1.3.0
		allure: Allure 1.2.8
		amecsapi: Amecs API 1.1.3+mc1.16.5
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		anvil_crushing_recipes: Anvil Crushing Recipes 1.0+MC1.16.2-1.16.5
		appleskin: AppleSkin 1.0.11
		appletreesrev: Apple Trees Revived 1.2
		architectury: Architectury 1.10.139
		artifice: Artifice 0.13.2+1.16.3
		autoclicker-fabric: Auto Clicker 1.0.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		autoswitch: AutoSwitch 3.1.0
		autoswitch-api: AutoSwitch API 1.0.0
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		betterslabs: Betterslabs 1.1.4
		blastrod: Blast Rod 1.0.0+1.16
		blockmeter: Block Meter 1.16.3-fabric0.20.2-1.5.3
		blue_endless_jankson: jankson 1.2.0
		bundlesplus: bundles plus 0.1.5
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-util: Cardinal Components API (utilities) 2.7.5
		carpet: Carpet Mod in Fabric 1.4.21
		carrier: Carrier 1.7.5
		charm: Charm 2.3.2
		chorus_links: Chorus Links 1.2.2
		clipboards: Clipboards 1.1.0+1.16.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		convth: Convenient Things 0.9.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		custom-fog: Custom Fog 1.4.0
		custom_piglin_bartering: {mod_name} 1.2.1+MC1.16-1.16.5
		darkness: True Darkness 1.6.58
		dataloader: Data Loader 2.1.0+mc1.16.1
		dispenser_configurator: Dispenser Configurator 1.0.1+MC1.16.4-1.16.5
		ducts: Ducts 1.0.4
		dynamicfps: Dynamic FPS 2.0.1
		easyautocrafting: EasyAutoCrafting 1.1+1.16
		entityculling: EntityCulling-Fabric 1.2.1
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabrication: Fabrication 1.3.4
		fabricloader: Fabric Loader 0.11.3
		fallingtree: FallingTree 2.11.0
		fastchest: FastChest 1.2+1.16
		fastfurnace: FastFurnace 2.4
		fiber: fiber 0.23.0-2
		flowstone: Flowstone 3.0.1+1.16
		goldenhoppers: Golden Hoppers 1.0.1
		hydrogen: Hydrogen 0.2
		inventoryhud: Inventory HUD + 3.2.2
		invisframes: Invisible Frames 2.0.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kirin: Kirin UI 1.7-1.16.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lapisreserve: Lapis Reserve 1.0.6
		lepton: Lepton-Fabric 1.16.5-1.0.0
		libblockattributes: LibBlockAttributes 0.8.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.1.0+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.4
		map_atlases: Map Atlases 1.2.5
		minecraft: Minecraft 1.16.5
		miniextras: Mini Extras Mod 1.2.1
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.16.9
		morerespawnanchors: More Respawn Anchors 1.0.1
		moundertweaks: MounderTweaks 1.4.2
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		nicetohave: Nice to Have 1.3.5
		oaktree: Oak Tree 0.4.2-beta
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_aeonbits_owner_owner: owner 1.0.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		packed_cobblestone: Packed Cobblestone 1.0.0
		pconfig: Paradox Config 0.3.6-alpha
		phosphor: Phosphor 0.7.1+build.11
		piglib: Piglib 1.0.3+1.16.5
		plantable_pots: Plantable Flower Pots 1.0.0
		presencefootsteps: Presence Footsteps r29+1.16.4
		pride: Pride Lib 1.0.0+1.16
		programmerartinjector: Programmer Art Injector 1.2.1
		quickshulker: Quick Shulker 1.1.14-1.16
		raisedclouds: Raised Clouds 1.0.0
		randompatches: RandomPatches 2.4.5-fabric
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		redbits: Red Bits 1.8.0
		redstonebits: Redstone Bits 1.2.2
		reroll: Reroll 1.2.0-1.16.5
		rhino: Rhino 1.7.13-build.14
		roughlyenoughitems: Roughly Enough Items 5.11.188
		roughlyenoughitems-api: REI (API) 5.11.188
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.188
		roughlyenoughitems-runtime: REI (Runtime) 5.11.188
		shiftyitems: Shifty Items 1.0.1-1.16
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.2
		spinnery: Spinnery 3.2.1
		spruceui: SpruceUI 2.0.4+1.16
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		statement: Statement 4.0.0+1.16.2
		strawgolem: Strawgolem 1.9.4
		supershulkers: Super Shulkers 0.1.0
		thats-my-chest: That's My Chest! 1.1.0
		tool_action_helper: Tool Action Helper 1.0.1
		tweed: Tweed API 3.0.0-beta.22
		water-erosion: Water Erosion 1.1.1
		whereisit: Where Is It 1.11.7
		wthit: wthit 2.5.4
		xp_storage: XP Storage 1.4+1.16.5
	Player Count: 1 / 8; [class_3222['Dead_E'/138, l='ServerLevel[New World]', x=31.61, y=64.00, z=162.66]]
	Data Packs: vanilla (incompatible), file/Default Anvil Crushing Recipes (incompatible), file/Default Anvil Crushing Recipes.zip (incompatible), file/Dispenser Configurators (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by InBlackOut** [comment]
The same thing happens to me, I am begging the creator of this beautiful mod to fix this :c
