### ISSUE TITLE
Rotator placement crashes Minecraft

### ISSUE THREAD

**Issue by Disketaa** [Shnupbups/redstone-bits#22]

**Comment by Shnupbups** [comment]
Could you provide the crash log please?

**Comment by Shnupbups** [comment]
I think I might have found and fixed the issue in 1.8.1... in future, it would really help if you could provide a crash log.

**Comment by Disketaa** [comment]
Thanks for the fix, I'm busy these days, so can't check out and confirm the fix yet

**Comment by Disketaa** [comment]
And provide a crush log

**Comment by Disketaa** [comment]
[crash-2022-05-27_14.35.47-client.txt](https://github.com/Shnupbups/redstone-bits/files/8793125/crash-2022-05-27_14.35.47-client.txt)

**Comment by Shnupbups** [comment]
Yes, that's the crash I fixed. Should be resolved in version 1.8.1

**Comment by Disketaa** [comment]
It works, thanks
