### ISSUE TITLE
Adder model suggestion

### ISSUE THREAD

**Issue by Disketaa** [Shnupbups/redstone-bits#23]
Greetings, it's me again. Sorry for writing me here, I didn't found discord link or smth. 
Well, I create something like this, so If you like it, I'll can do rest of the **adder** models: 

![image](https://user-images.githubusercontent.com/76956762/170891470-f1cc8a47-6475-403b-b459-182127b8d965.png)
_(You can delete this issue later)_

**Comment by Shnupbups** [comment]
I'd rather stick to a vanilla style as much as possible, and would therefore prefer to not have an actual number written on the block. Feel free to release it as a resource pack though!

I'm also not exactly an artist, so if you or anyone wanted to try their hands at improving the textures (and potentially making new ones) I'd be grateful.

**Comment by Disketaa** [comment]
By the way, I'm currently **revision** / **rethink** crafts and logic of the placer, breaker and checker. I did copper variants for them to actualize copper in crafts a bit. Its also create a smething like a second tier of redstone. 

![image](https://user-images.githubusercontent.com/76956762/171044850-7d84a112-ae08-4f5b-835f-4bb830ad0dad.png)
![image](https://user-images.githubusercontent.com/76956762/171044856-80b5fc36-2fc8-4ef1-85e1-0c005ef334ab.png)
![image](https://user-images.githubusercontent.com/76956762/171044863-997d05a2-3874-4ea6-a6ed-8c7e77b0484a.png)
